name: publish

on: [push, workflow_dispatch]

jobs:
  publish-grid-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: login
      - uses: actions/checkout@v2
    
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
             docker build . --tag ghcr.io/abosaad11/grid:0.5
             docker run ghcr.io/abosaad11/grid:0.5
             docker push ghcr.io/abosaad11/grid:0.5
